from django.db import models

# django rest framework 쓰기 위한 model


class CatSearch(models.Model):
    breed = models.CharField(max_length=50)
    코코 = models.IntegerField(default=0)
    보리 = models.IntegerField(default=0)
    모모 = models.IntegerField(default=0)
    까미 = models.IntegerField(default=0)
    하루 = models.IntegerField(default=0)
    미미 = models.IntegerField(default=0)
    모찌 = models.IntegerField(default=0)
    나비 = models.IntegerField(default=0)
    치즈 = models.IntegerField(default=0)
    두부 = models.IntegerField(default=0)
    구름이 = models.IntegerField(default=0)
    누누 = models.IntegerField(default=0)
    라떼 = models.IntegerField(default=0)
    초코 = models.IntegerField(default=0)
    까망이 = models.IntegerField(default=0)
    천둥 = models.IntegerField(default=0)
    번개 = models.IntegerField(default=0)
    써니 = models.IntegerField(default=0)
    기쁨이 = models.IntegerField(default=0)
    해피 = models.IntegerField(default=0)
    구찌 = models.IntegerField(default=0)
    샤넬 = models.IntegerField(default=0)
    미키 = models.IntegerField(default=0)
    루피 = models.IntegerField(default=0)
    몰랑 = models.IntegerField(default=0)
    토리 = models.IntegerField(default=0)
    헨리 = models.IntegerField(default=0)
    조이 = models.IntegerField(default=0)

    def __str__(self):
        return self.breed


class DogSearch(models.Model):
    breed = models.CharField(max_length=50)
    코코 = models.IntegerField(default=0)
    보리 = models.IntegerField(default=0)
    콩이 = models.IntegerField(default=0)
    초코 = models.IntegerField(default=0)
    두부 = models.IntegerField(default=0)
    호두 = models.IntegerField(default=0)
    별이 = models.IntegerField(default=0)
    사랑이 = models.IntegerField(default=0)
    까미 = models.IntegerField(default=0)
    몽이 = models.IntegerField(default=0)
    토리 = models.IntegerField(default=0)
    마루 = models.IntegerField(default=0)
    뭉치 = models.IntegerField(default=0)
    해피 = models.IntegerField(default=0)
    꼬미 = models.IntegerField(default=0)
    망고 = models.IntegerField(default=0)
    똘이 = models.IntegerField(default=0)
    쿠키 = models.IntegerField(default=0)
    사랑이 = models.IntegerField(default=0)
    콩이 = models.IntegerField(default=0)
    둥이 = models.IntegerField(default=0)
    모찌 = models.IntegerField(default=0)
    만두 = models.IntegerField(default=0)
    봄이 = models.IntegerField(default=0)
    초롱이 = models.IntegerField(default=0)
    레오 = models.IntegerField(default=0)
    뚱이 = models.IntegerField(default=0)
    루이 = models.IntegerField(default=0)
    토토 = models.IntegerField(default=0)
    구름이 = models.IntegerField(default=0)
    가을이 = models.IntegerField(default=0)
    송이 = models.IntegerField(default=0)
    모모 = models.IntegerField(default=0)
    땅콩 = models.IntegerField(default=0)
    루비 = models.IntegerField(default=0)
    짱아 = models.IntegerField(default=0)
    흰둥이 = models.IntegerField(default=0)
    뽀미 = models.IntegerField(default=0)
    미미 = models.IntegerField(default=0)
    장군이 = models.IntegerField(default=0)
    아롱이 = models.IntegerField(default=0)
    두리 = models.IntegerField(default=0)
    여름이 = models.IntegerField(default=0)
    밍키 = models.IntegerField(default=0)

    def __str__(self):
        return self.breed
