# Generated by Django 4.0.2 on 2022-08-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_remove_dogsearch_봄'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogsearch',
            name='구름',
        ),
    ]
